<a href="https://colab.research.google.com/github/anuvishalp/Python_basics/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
### numpy- python
import numpy as np


In [13]:

b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [ ]:
c=np.random

##indexing and slicing


In [6]:
arr=np.array([[1,2,3],[4,5,6]])
arr[0][1]
arr[0,1]


np.int64(2)

In [10]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [11]:
arr[1,2]

np.int64(6)

In [ ]:
""" CHEATSHEET of NUMPY -Python
📌 1. Creating Arrays
🟦 Basic Creation
python
import numpy as np

a = np.array([1, 2, 3])              # 1D array
b = np.array([[1, 2], [3, 4]])       # 2D array

🟦 Predefined Arrays
python
np.zeros((2,3))      # 2x3 matrix of zeros
np.ones((3,3))       # 3x3 matrix of ones
np.full((2,2), 7)    # filled with 7
np.eye(4)            # 4x4 identity matrix

🟦 Ranges
python
np.arange(0, 10, 2)      # [0,2,4,6,8]
np.linspace(0, 1, 5)     # 5 points between 0 and 1

📌 2. Array Attributes
Attribute	Meaning
a.ndim	Number of dimensions
a.shape	Rows × Columns
a.size	Total elements
a.dtype	Data type
a.itemsize	Bytes per element

python
a = np.array([[1,2,3],[4,5,6]])
a.shape      # (2,3)
a.ndim       # 2
a.dtype      # int64
📌 3. Indexing & Slicing
🟦 Basic Slicing
python
a = np.array([10,20,30,40,50])
a[1:4]       # [20,30,40]
🟦 2D Slicing
python
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b[0:2, 1:]   # rows 0–1, columns 1–end
🟦 Boolean Indexing
python
a[a > 25]     # elements > 25
🟦 Fancy Indexing
python
a[[0,2,4]]    # pick specific indices
📌 4. Reshaping & Manipulation
🟦 Reshape
python
a = np.arange(6)
a.reshape(2,3)
🟦 Flatten
python
a.flatten()
a.ravel()     # faster, returns view
🟦 Transpose
python
a.T
🟦 Concatenate / Stack
python
np.concatenate([a1, a2])
np.vstack([a1, a2])
np.hstack([a1, a2])
📌 5. Arithmetic & Vectorization
NumPy applies operations element‑wise.

python
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b         # [5,7,9]
a * b         # [4,10,18]
a ** 2        # [1,4,9]
📌 6. Broadcasting
NumPy automatically expands shapes when compatible.

python
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

a + b
Broadcasting rule: dimensions must match or be 1.

📌 7. Useful Math Functions
python
np.sum(a)
np.mean(a)
np.std(a)
np.min(a)
np.max(a)
np.argmin(a)
np.argmax(a)
np.sqrt(a)
np.exp(a)
np.log(a)
📌 8. Linear Algebra
python
np.dot(a, b)          # dot product
np.matmul(a, b)       # matrix multiplication
np.linalg.inv(A)      # inverse
np.linalg.det(A)      # determinant
np.linalg.eig(A)      # eigenvalues/vectors
📌 9. Random Module
python
np.random.rand(3,2)        # uniform [0,1)
np.random.randn(3,2)       # normal distribution
np.random.randint(1,10,5)  # random ints
np.random.seed(42)         # reproducibility
📌 10. Handling Missing Values
python
np.isnan(a)
np.nanmean(a)
np.nan_to_num(a)
📌 11. File I/O
python
np.save('arr.npy', a)
np.load('arr.npy')

np.savetxt('data.csv', a, delimiter=',')
np.loadtxt('data.csv', delimiter=',')
📌 12. Performance Tips
Prefer vectorized operations over Python loops

Use views (ravel) instead of copies (flatten)

Use astype() to convert dtypes efficiently

Use broadcasting instead of manual expansion """

In [16]:
import numpy as np
arr=np.array([
    [0,1,2,3],
 [4,5,6,7],
  [8,9,10,11],
   [12,13,14,15]])
print(arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [17]:
print(arr[1,2]) ## print the element in 2nd row,3rd column

6


In [18]:
print(arr[3,1])


13


In [19]:
print(arr[0])

[0 1 2 3]


In [20]:
print(arr[:,3])

[ 3  7 11 15]


In [21]:
print(arr[:,1])

[ 1  5  9 13]


In [22]:
print(arr[:2,:2])

[[0 1]
 [4 5]]


In [23]:
print(arr[1:3,1:3])

[[ 5  6]
 [ 9 10]]


In [24]:
print(arr[-2:])

[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
print(arr[:3,-2])

In [28]:
import numpy as np

a = np.array([1, 2, 3])              # 1D array
b = np.array([[1, 2], [3, 4]])       # 2D array
b

array([[1, 2],
       [3, 4]])

In [30]:
np.zeros((2,3))      # 2x3 matrix of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((3,3))       # 3x3 matrix of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.full((2,2), 7)    # filled with 7


array([[7, 7],
       [7, 7]])

In [33]:
np.eye(4)            # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.arange(0, 10, 2)      # [0,2,4,6,8]

array([0, 2, 4, 6, 8])

In [35]:
np.linspace(0, 1, 5)     # 5 points between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
a = np.array([[1,2,3],[4,5,6]])
a.shape      # (2,3)
a.ndim       # 2
a.dtype      # int64

dtype('int64')

In [37]:
a = np.array([10,20,30,40,50])
a[1:4]       # [20,30,40]

array([20, 30, 40])

In [38]:
##🟦 2D Slicing

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b[0:2, 1:]   # rows 0–1, columns 1–end

array([[2, 3],
       [5, 6]])

In [ ]:
##🟦 Boolean Indexing
a[a > 25]     # elements > 25

In [ ]:
##🟦 Fancy Indexing
a[[0,2,4]]    # pick specific indices

In [ ]:
##📌 4. Reshaping & Manipulation ->🟦 Reshape

a = np.arange(6)
a.reshape(2,3)

In [ ]:
##🟦 Flatten

a.flatten()
a.ravel()     # faster, returns view

In [ ]:
##🟦 Transpose
a.T

In [ ]:
##🟦 Concatenate / Stack
np.concatenate([a1, a2])
np.vstack([a1, a2])
np.hstack([a1, a2])

In [ ]:
##📌 5. Arithmetic & Vectorization -> NumPy applies operations element‑wise.

a = np.array([1,2,3])
b = np.array([4,5,6])

a + b         # [5,7,9]

In [ ]:
a * b         # [4,10,18]

In [ ]:
a ** 2        # [1,4,9]

In [ ]:
##📌 6. Broadcasting -> NumPy automatically expands shapes when compatible.

a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

a + b
Broadcasting rule: dimensions must match or be 1.


In [ ]:
###📌 7. Useful Math Functions
np.sum(a)
np.mean(a)
np.std(a)
np.min(a)
np.max(a)
np.argmin(a)
np.argmax(a)
np.sqrt(a)
np.exp(a)
np.log(a)

In [ ]:
###📌 8. Linear Algebra

np.dot(a, b)          # dot product
np.matmul(a, b)       # matrix multiplication
np.linalg.inv(A)      # inverse
np.linalg.det(A)      # determinant
np.linalg.eig(A)      # eigenvalues/vectors

In [ ]:
###📌 9. Random Module
np.random.rand(3,2)        # uniform [0,1)
np.random.randn(3,2)       # normal distribution
np.random.randint(1,10,5)  # random ints
np.random.seed(42)         # reproducibility

In [ ]:
###📌 10. Handling Missing Values

np.isnan(a)
np.nanmean(a)
np.nan_to_num(a)

In [ ]:
###📌 11. File I/O
np.save('arr.npy', a)
np.load('arr.npy')

np.savetxt('data.csv', a, delimiter=',')
np.loadtxt('data.csv', delimiter=',')